apigw:
  redis:
    host: "127.0.0.1"
    port: "6379"
    password: ""
  proxy:
    - name: uias
      server:
        - location:
            path: /uias
            backend:
              host: 'http://10.10.10.14:18180'
              url: /
    - name: newxxx
      server:
        - location:
            path: /outs
            backend:
              host: 'http://10.10.10.14:18180'
              url: /internal/v1/xxx/user/signin
